version: '3.9'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/search_app
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8080

  database:
    image: 'postgres:latest'
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=search_app'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=auto_test'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: